1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [1]:
import numpy as np

In [2]:
arr = np.arange(6)


In [3]:
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

2.Given a NumPy array 'arr', check if its data type is float64.

In [7]:
import numpy as np


In [8]:
arr = np.array([0.1, 0.2, 0.3, 0.4, 0.5])  # Example array


In [9]:
is_float64 = arr.dtype == np.float64


In [10]:
print("Is the array of type float64?", is_float64)

Is the array of type float64? True


3 Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [11]:
import numpy as np

In [12]:
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)


In [20]:
print("Array:", arr)

Array: [1.+2.j 3.+4.j 5.+6.j]


In [23]:
print("Data type:", arr.dtype)


Data type: complex128


4.Convert an existing NumPy array 'arr' of integers to float32 data type.

In [24]:
import numpy as np

In [25]:
arr = np.array([1, 2, 3, 4, 5])


In [26]:
arr_float32 = arr.astype(np.float32)


In [27]:
print("Original array:", arr)
print("Original data type:", arr.dtype)
print("Converted array:", arr_float32)
print("Converted data type:", arr_float32.dtype)


Original array: [1 2 3 4 5]
Original data type: int64
Converted array: [1. 2. 3. 4. 5.]
Converted data type: float32


5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [28]:
import numpy as np


In [29]:
arr = np.array([1.123456789, 2.987654321, 3.1415926535], dtype=np.float64)


In [30]:
arr_float32 = arr.astype(np.float32)


In [31]:
print("Original array:", arr)
print("Original data type:", arr.dtype)
print("Converted array:", arr_float32)
print("Converted data type:", arr_float32.dtype)


Original array: [1.12345679 2.98765432 3.14159265]
Original data type: float64
Converted array: [1.1234568 2.9876542 3.1415927]
Converted data type: float32


6 Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.

In [39]:
import numpy as np
arr = np.ones((2,1))

In [40]:
arr.shape

(2, 1)

In [41]:
arr.size

2

In [44]:
print("Data type:", arr.dtype)


Data type: float64


7.Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [53]:
import  numpy as np
def array_dimension(arr):
    
        return arr.ndim


arr1 = np.array([1, 2, 3, 4])
print(array_dimension(arr1))

1


8.Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

In [56]:
import numpy as np

# Define the function
def item_size_info(arr):
    
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size

# Create NumPy arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1.0, 2.0], [3.0, 4.0]])
arr3 = np.array([[[1], [2]], [[3], [4]]])

# Call the function and print the results
print(item_size_info(arr1))  
print(item_size_info(arr2)) 
print(item_size_info(arr3))  

(8, 32)
(8, 32)
(8, 32)


9.Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [1]:
import numpy as np

def array_strides(array):
    return array.strides
# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print(strides)  # Output will be something like (24, 8)


(24, 8)


10.Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [2]:
import numpy as np

def shape_stride_relationship(array):
    return array.shape, array.strides
# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print(f"Shape: {shape}")
print(f"Strides: {strides}")


Shape: (2, 3)
Strides: (24, 8)


11.Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

In [3]:
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)
 
    # Example usage
n = 5
zeros_array = create_zeros_array(n)
print(zeros_array)  # Output will be: [0. 0. 0. 0. 0.]


[0. 0. 0. 0. 0.]


12.Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [4]:
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
# Example usage
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


13.Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [5]:
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
# Example usage
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print(range_array)


[0 2 4 6 8]


14.Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [6]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
# Example usage
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print(linear_space_array)


[0.   0.25 0.5  0.75 1.  ]


15.Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

In [7]:
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)
 
# Example usage
n = 4
identity_matrix = create_identity_matrix(n)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


16.Write a function that takes a Python list and converts it into a NumPy array.

In [8]:
import numpy as np

def list_to_numpy_array(py_list):
    return np.array(py_list)
# Example usage
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)
print(numpy_array)


[1 2 3 4 5]


17.Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

In [9]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5])

view_array = original_array.view()

print("Original array:", original_array)
print("View array:", view_array)

view_array[0] = 99
print("Modified view array:", view_array)
print("Original array after modifying the view array:", original_array)


Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]
Modified view array: [99  2  3  4  5]
Original array after modifying the view array: [99  2  3  4  5]


18.Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [10]:
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

concatenated_array_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concatenated_array_axis0)

concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", concatenated_array_axis1)


Concatenated along axis 0:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated along axis 1:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
concatenate`.

In [11]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [9, 10]])

concatenated_array = np.concatenate((array1, array2), axis=1)

print("Array 1:")
print(array1)

print("Array 2:")
print(array2)

print("Concatenated array (horizontally):")
print(concatenated_array)


Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[ 7  8]
 [ 9 10]]
Concatenated array (horizontally):
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


20.Write a function that vertically stacks multiple NumPy arrays given as a list.

In [13]:
import numpy as np

def vertical_stack(arrays):
    return np.vstack(arrays)

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15]])

stacked_array = vertical_stack([array1, array2, array3])
print("Vertically stacked array:")
print(stacked_array)


Vertically stacked array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


21.Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

In [14]:
import numpy as np

def vertical_stack(arrays):
    return np.vstack(arrays)

# Example usage
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15]])

# Stack the arrays vertically
stacked_array = vertical_stack([array1, array2, array3])
print("Vertically stacked array:")
print(stacked_array)


Vertically stacked array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


22.Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [16]:
import numpy as np

def generate_equally_spaced_array(start=0, stop=1, num=10):
    return np.linspace(start, stop, num)

array = generate_equally_spaced_array()
print("Array of 10 equally spaced values between 0 and 1:")
print(array)


Array of 10 equally spaced values between 0 and 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


23.Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

In [17]:
import numpy as np

def generate_logarithmically_spaced_array(start=1, stop=1000, num=5):
    return np.logspace(np.log10(start), np.log10(stop), num)

log_spaced_array = generate_logarithmically_spaced_array()
print("Array of 5 logarithmically spaced values between 1 and 1000:")
print(log_spaced_array)


Array of 5 logarithmically spaced values between 1 and 1000:
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


24.Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [18]:
import numpy as np
import pandas as pd

# Generate a NumPy array with random integers between 1 and 100
np_array = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(np_array, columns=['Column1', 'Column2', 'Column3'])

print("Pandas DataFrame:")
print(df)


Pandas DataFrame:
   Column1  Column2  Column3
0       49        3       19
1       54       10      100
2       34       65       21
3       14       88       17
4       63       42       48


25.Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [19]:
import pandas as pd
import numpy as np

def replace_negative_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df


data = {
    'A': [10, -20, 30, -40, 50],
    'B': [-1, 2, -3, 4, -5]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace negative values in column 'A'
df = replace_negative_with_zero(df, 'A')

print("\nDataFrame after replacing negative values in column 'A':")
print(df)

# Replace negative values in column 'B'
df = replace_negative_with_zero(df, 'B')

print("\nDataFrame after replacing negative values in column 'B':")
print(df)


Original DataFrame:
    A  B
0  10 -1
1 -20  2
2  30 -3
3 -40  4
4  50 -5

DataFrame after replacing negative values in column 'A':
    A  B
0  10 -1
1   0  2
2  30 -3
3   0  4
4  50 -5

DataFrame after replacing negative values in column 'B':
    A  B
0  10  0
1   0  2
2  30  0
3   0  4
4  50  0


26.Access the 3rd element from the given NumPy array.

     arr = np.array([10, 20, 30, 40, 50])


In [20]:
import numpy as np

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

print("The 3rd element is:", third_element)


The 3rd element is: 30


27.Retrieve the element at index (1, 2) from the 2D NumPy array

arr_2d = np.array([[1, 2, 3],

                   [4, 5, 6],

                   [7, 8, 9]])


In [21]:
import numpy as np

# Given 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)


The element at index (1, 2) is: 6


28.Using boolean indexing, extract elements greater than 5 from the given NumPy array.


  arr = np.array([3, 8, 2, 10, 5, 7])


In [22]:
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

# Create a boolean mask for elements greater than 5
mask = arr > 5

# Use the mask to extract elements greater than 5
elements_greater_than_5 = arr[mask]

print("Elements greater than 5:", elements_greater_than_5)


Elements greater than 5: [ 8 10  7]


29.Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extract elements from index 2 to 5 (inclusive)
sliced_array = arr[2:6]

print("Elements from index 2 to 5 (inclusive):", sliced_array)


Elements from index 2 to 5 (inclusive): [3 4 5 6]


30.Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array

In [25]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]

print("Extracted sub-array:")
print(sub_array)


Extracted sub-array:
[[2 3]
 [5 6]]


31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [26]:
import numpy as np

def extract_elements_by_indices(arr_2d, indices):
    # Convert indices to a 2D array if necessary
    if np.ndim(indices) == 1:
        indices = np.array([indices])

    # Extract elements based on indices
    extracted_elements = arr_2d[indices[:, 0], indices[:, 1]]
    return extracted_elements

arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

indices = np.array([[0, 1],  # Element at (0, 1) -> 20
                    [1, 2],  # Element at (1, 2) -> 60
                    [2, 0]]) # Element at (2, 0) -> 70

extracted_elements = extract_elements_by_indices(arr_2d, indices)
print("Extracted elements:", extracted_elements)


Extracted elements: [20 60 70]


32.. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [27]:
import numpy as np

def filter_greater_than(arr, threshold):
    # Create a boolean mask where elements greater than the threshold are True
    mask = arr > threshold
    # Use the mask to filter the array
    filtered_array = arr[mask]
    return filtered_array

# Example usage
arr = np.array([1, 5, 8, 10, 2, 7])
threshold = 6

filtered_elements = filter_greater_than(arr, threshold)
print("Elements greater than the threshold:", filtered_elements)


Elements greater than the threshold: [ 8 10  7]


33.Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [28]:
import numpy as np

def extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3):
    # Convert indices to NumPy arrays (if they are not already)
    indices_dim1 = np.asarray(indices_dim1)
    indices_dim2 = np.asarray(indices_dim2)
    indices_dim3 = np.asarray(indices_dim3)
    
    # Ensure all index arrays are of the same length
    if not (len(indices_dim1) == len(indices_dim2) == len(indices_dim3)):
        raise ValueError("All index arrays must have the same length.")
    
    # Extract elements based on indices
    extracted_elements = arr_3d[indices_dim1, indices_dim2, indices_dim3]
    return extracted_elements

# Example usage
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                   [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

indices_dim1 = [0, 1, 2]  # Indices for the first dimension
indices_dim2 = [2, 1, 0]  # Indices for the second dimension
indices_dim3 = [1, 2, 0]  # Indices for the third dimension

extracted_elements = extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print("Extracted elements:", extracted_elements)


Extracted elements: [ 8 15 19]


34.Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

In [29]:
import numpy as np

def filter_elements(arr, condition1, condition2):
    # Ensure conditions are boolean arrays
    condition1 = np.asarray(condition1)
    condition2 = np.asarray(condition2)
    
    # Combine the conditions using logical AND
    combined_condition = condition1 & condition2
    
    # Use the combined condition to filter the array
    filtered_elements = arr[combined_condition]
    return filtered_elements

# Example usage
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Define conditions
condition1 = arr > 20        # Elements greater than 20
condition2 = arr < 60        # Elements less than 60

# Filter elements where both conditions are satisfied
filtered_elements = filter_elements(arr, condition1, condition2)
print("Filtered elements:", filtered_elements)


Filtered elements: [30 40 50]


35.Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [30]:
import numpy as np

def extract_elements_2d(arr_2d, row_indices, col_indices):
    # Convert indices to NumPy arrays (if they are not already)
    row_indices = np.asarray(row_indices)
    col_indices = np.asarray(col_indices)
    
    # Ensure all index arrays are of the same length
    if len(row_indices) != len(col_indices):
        raise ValueError("Row and column index arrays must have the same length.")
    
    # Extract elements based on row and column indices
    extracted_elements = arr_2d[row_indices, col_indices]
    return extracted_elements

# Example usage
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

row_indices = [0, 1, 2]  # Row indices
col_indices = [1, 2, 0]  # Column indices

extracted_elements = extract_elements_2d(arr_2d, row_indices, col_indices)
print("Extracted elements:", extracted_elements)


Extracted elements: [20 60 70]


36.Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [31]:
import numpy as np

# Given 2D NumPy array with shape (3, 3)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Scalar value to add
scalar_value = 5

# Add the scalar value to each element using broadcasting
result = arr + scalar_value

print("Original array:")
print(arr)
print("\nArray after adding scalar value of 5:")
print(result)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after adding scalar value of 5:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


37.Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [ ]:
import numpy as np

# Given arrays
arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # Shape (3, 4)

# Multiply each row of arr2 by the corresponding element in arr1
result = arr2 * arr1

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after broadcasting and multiplication:")
print(result)


38.Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [34]:
import numpy as np

# Given arrays
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])  # Shape (4, 3)

# Reshape arr1 to (4, 4) for broadcasting
# Since arr1 has a different number of columns than arr2, 
# it needs to be reshaped to ensure the broadcasting works.
# We can use `np.broadcast_to` to achieve this.
arr1_broadcasted = np.broadcast_to(arr1, (arr2.shape[0], arr1.shape[1]))

# Add arr1 to each row of arr2
result = arr2 + arr1_broadcasted[:, :arr2.shape[1]]

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after broadcasting and addition:")
print(result)


Array arr1:
[[1 2 3 4]]

Array arr2:
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]

Result after broadcasting and addition:
[[ 6  8 10]
 [ 9 11 13]
 [12 14 16]
 [15 17 19]]


39.Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [35]:
import numpy as np

# Given arrays
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])      # Shape (1, 3)

# Add the arrays using broadcasting
result = arr1 + arr2

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nResult after broadcasting and addition:")
print(result)


Array arr1:
[[1]
 [2]
 [3]]

Array arr2:
[[4 5 6]]

Result after broadcasting and addition:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


40.Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [36]:
import numpy as np

# Given arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])   # Shape (2, 3)

arr2 = np.array([[7, 8],
                 [9, 10]])     # Shape (2, 2)

# Reshape arr2 to (2, 1, 2) for broadcasting
arr2_reshaped = arr2[:, :, np.newaxis]  # Shape (2, 2, 1)

# Reshape arr1 to (2, 1, 3) for broadcasting
arr1_reshaped = arr1[:, np.newaxis, :]  # Shape (2, 1, 3)

# Perform element-wise multiplication
result = arr1_reshaped * arr2_reshaped

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)
print("\nReshaped arr1:")
print(arr1_reshaped)
print("\nReshaped arr2:")
print(arr2_reshaped)
print("\nResult after broadcasting and multiplication:")
print(result)


Array arr1:
[[1 2 3]
 [4 5 6]]

Array arr2:
[[ 7  8]
 [ 9 10]]

Reshaped arr1:
[[[1 2 3]]

 [[4 5 6]]]

Reshaped arr2:
[[[ 7]
  [ 8]]

 [[ 9]
  [10]]]

Result after broadcasting and multiplication:
[[[ 7 14 21]
  [ 8 16 24]]

 [[36 45 54]
  [40 50 60]]]


41.Calculate column wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [37]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate column-wise mean
column_mean = np.mean(arr, axis=0)

print("Original array:")
print(arr)
print("\nColumn-wise mean:")
print(column_mean)


Original array:
[[1 2 3]
 [4 5 6]]

Column-wise mean:
[2.5 3.5 4.5]


42.Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [38]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find maximum value in each row
row_max = np.amax(arr, axis=1)

print("Original array:")
print(arr)
print("\nMaximum value in each row:")
print(row_max)


Original array:
[[1 2 3]
 [4 5 6]]

Maximum value in each row:
[3 6]


43.For the given array, find indices of maximum value in each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find indices of maximum values in each column
max_indices = np.argmax(arr, axis=0)

print("Original array:")
print(arr)
print("\nIndices of maximum values in each column:")
print(max_indices)


Original array:
[[1 2 3]
 [4 5 6]]

Indices of maximum values in each column:
[1 1 1]


44.For the given array, apply custom function to calculate moving sum along rows.

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [40]:
import numpy as np

def moving_sum(arr, window_size):
    # Get the number of rows and columns
    num_rows, num_cols = arr.shape
    
    # Initialize the result array with zeros
    result = np.zeros((num_rows, num_cols - window_size + 1))
    
    # Compute moving sum for each row
    for i in range(num_rows):
        row = arr[i]
        # Compute the moving sum using a sliding window
        for j in range(num_cols - window_size + 1):
            result[i, j] = np.sum(row[j:j + window_size])
    
    return result

# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Window size for moving sum
window_size = 2

# Apply the custom moving sum function
moving_sum_result = moving_sum(arr, window_size)

print("Original array:")
print(arr)
print("\nMoving sum with window size of 2:")
print(moving_sum_result)


Original array:
[[1 2 3]
 [4 5 6]]

Moving sum with window size of 2:
[[ 3.  5.]
 [ 9. 11.]]


45.In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])

In [41]:
import numpy as np

# Given array
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if all elements in each column are even
all_even = np.all(arr % 2 == 0, axis=0)

print("Original array:")
print(arr)
print("\nAre all elements in each column even?")
print(all_even)


Original array:
[[2 4 6]
 [3 5 7]]

Are all elements in each column even?
[False False False]


46.Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.


original_array = np.array([1, 2, 3, 4, 5, 6])

In [42]:
import numpy as np

# Given array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Define new shape dimensions (m, n)
m, n = 2, 3  # Example dimensions

# Reshape the array
reshaped_matrix = original_array.reshape(m, n)

print("Original array:")
print(original_array)
print("\nReshaped matrix:")
print(reshaped_matrix)


Original array:
[1 2 3 4 5 6]

Reshaped matrix:
[[1 2 3]
 [4 5 6]]


47.Create a function that takes a matrix as input and returns the flattened array.

   input_matrix = np.array([[1, 2, 3], [4, 5, 6]])


In [43]:
import numpy as np

def flatten_matrix(matrix):
   
    return matrix.flatten()

# Given matrix
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the matrix
flattened_array = flatten_matrix(input_matrix)

print("Original matrix:")
print(input_matrix)
print("\nFlattened array:")
print(flattened_array)


Original matrix:
[[1 2 3]
 [4 5 6]]

Flattened array:
[1 2 3 4 5 6]


48.Write a function that concatenates two given arrays along a specified axis.


array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])



In [1]:
import numpy as np

def concatenate_arrays(array1, array2, axis):
    """
    Concatenates two given arrays along a specified axis.

    Parameters:
    array1 (np.ndarray): The first array to concatenate.
    array2 (np.ndarray): The second array to concatenate.
    axis (int): The axis along which the arrays will be concatenated.

    Returns:
    np.ndarray: The concatenated array.
    """
    return np.concatenate((array1, array2), axis=axis)

# Given arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:")
print(concatenated_axis0)

# Concatenate along axis 1 (columns)
concatenated_axis1 = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along axis 1:")
print(concatenated_axis1)


Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


49.Create a function that splits an array into multiple sub-arrays along a specified axis


original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [2]:
import numpy as np

def split_array(array, indices_or_sections, axis=0):
    """
    Splits an array into multiple sub-arrays along a specified axis.

    Parameters:
    array (np.ndarray): The input array to split.
    indices_or_sections (int or 1-D array): If an integer, it determines the number of equal-sized sub-arrays to create.
                                            If a 1-D array, it determines the indices at which the array is split.
    axis (int): The axis along which to split the array. Default is 0.

    Returns:
    list of np.ndarray: A list of sub-arrays.
    """
    return np.split(array, indices_or_sections, axis=axis)

# Given array
original_array = np.array([[1, 2, 3], 
                           [4, 5, 6], 
                           [7, 8, 9]])

# Split into 3 equal parts along axis 0 (rows)
split_arrays_axis0 = split_array(original_array, 3, axis=0)
print("Split into 3 equal parts along axis 0:")
for sub_array in split_arrays_axis0:
    print(sub_array)

# Split at specific indices along axis 1 (columns)
split_arrays_axis1 = split_array(original_array, [1, 2], axis=1)
print("\nSplit at specific indices [1, 2] along axis 1:")
for sub_array in split_arrays_axis1:
    print(sub_array)


Split into 3 equal parts along axis 0:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Split at specific indices [1, 2] along axis 1:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


50.Write a function that inserts and then deletes elements from a given array at specified indices.


original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]

values_to_insert = [10, 11]

indices_to_delete = [1, 3]


In [3]:
import numpy as np

def insert_and_delete_elements(array, indices_to_insert, values_to_insert, indices_to_delete):
    """
    Inserts values into the array at specified indices and then deletes elements from the array at specified indices.

    Parameters:
    array (np.ndarray): The original array.
    indices_to_insert (list of int): The indices at which to insert the values.
    values_to_insert (list of int): The values to insert at the specified indices.
    indices_to_delete (list of int): The indices of the elements to delete from the array.

    Returns:
    np.ndarray: The resulting array after insertion and deletion.
    """
    # Insert values at specified indices
    array = np.insert(array, indices_to_insert, values_to_insert)
    
    # Adjust indices to delete due to prior insertions
    indices_to_delete_adjusted = np.sort(indices_to_delete)
    
    # Delete elements at specified indices
    array = np.delete(array, indices_to_delete_adjusted)
    
    return array

# Given array
original_array = np.array([1, 2, 3, 4, 5])

# Indices to insert values
indices_to_insert = [2, 4]
values_to_insert = [10, 11]

# Indices to delete values
indices_to_delete = [1, 3]

# Perform insertion and deletion
result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Original array:")
print(original_array)
print("\nArray after insertion and deletion:")
print(result_array)


Original array:
[1 2 3 4 5]

Array after insertion and deletion:
[ 1 10  4 11  5]


 51.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [4]:
import numpy as np

# Create a NumPy array arr1 with random integers
arr1 = np.random.randint(1, 11, size=10)  # Random integers between 1 and 10, size 10

# Create a NumPy array arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise addition
result_array = arr1 + arr2

print("Array arr1 (random integers):")
print(arr1)
print("\nArray arr2 (integers from 1 to 10):")
print(arr2)
print("\nResulting array after element-wise addition:")
print(result_array)


Array arr1 (random integers):
[ 6  6  5  8  5  1  6  9  6 10]

Array arr2 (integers from 1 to 10):
[ 1  2  3  4  5  6  7  8  9 10]

Resulting array after element-wise addition:
[ 7  8  8 12 10  7 13 17 15 20]


52.Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [5]:
import numpy as np

# Create the arrays
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

# Subtract arr2 from arr1 element-wise
result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of arr1 - arr2:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of arr1 - arr2: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


53.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [6]:
import numpy as np

# Create a NumPy array arr1 with random integers between 1 and 10, size 5
arr1 = np.random.randint(1, 11, size=5)

# Create a NumPy array arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise multiplication
result_array = arr1 * arr2

print("Array arr1 (random integers):")
print(arr1)
print("\nArray arr2 (integers from 1 to 5):")
print(arr2)
print("\nResulting array after element-wise multiplication:")
print(result_array)


Array arr1 (random integers):
[ 8  9  1  9 10]

Array arr2 (integers from 1 to 5):
[1 2 3 4 5]

Resulting array after element-wise multiplication:
[ 8 18  3 36 50]


54.Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [7]:
import numpy as np

# Create a NumPy array arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create a NumPy array arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division
result_array = arr1 / arr2

print("Array arr1 (even integers from 2 to 10):")
print(arr1)
print("\nArray arr2 (integers from 1 to 5):")
print(arr2)
print("\nResulting array after element-wise division:")
print(result_array)


Array arr1 (even integers from 2 to 10):
[ 2  4  6  8 10]

Array arr2 (integers from 1 to 5):
[1 2 3 4 5]

Resulting array after element-wise division:
[2. 2. 2. 2. 2.]


55.Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise

In [8]:
import numpy as np

# Create a NumPy array arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create a NumPy array arr2 with integers from 1 to 5, reversed
arr2 = arr1[::-1]

# Perform element-wise exponentiation
result_array = arr1 ** arr2

print("Array arr1 (integers from 1 to 5):")
print(arr1)
print("\nArray arr2 (reversed integers from 1 to 5):")
print(arr2)
print("\nResulting array after element-wise exponentiation:")
print(result_array)


Array arr1 (integers from 1 to 5):
[1 2 3 4 5]

Array arr2 (reversed integers from 1 to 5):
[5 4 3 2 1]

Resulting array after element-wise exponentiation:
[ 1 16 27 16  5]


56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])


In [10]:
import numpy as np

def count_substring_occurrences(arr, substring):
    """
    Counts the occurrences of a specific substring within a NumPy array of strings.

    Parameters:
    arr (np.ndarray): A NumPy array of strings.
    substring (str): The substring to count.

    Returns:
    int: The number of occurrences of the substring in the array.
    """
    # Use np.char.count to count occurrences of the substring in each element
    counts = np.char.count(arr, substring)
    
    # Sum up the counts to get the total occurrences
    total_count = np.sum(counts)
    
    return total_count

# Given array
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Substring to count
substring = 'hello'

# Count occurrences
occurrences = count_substring_occurrences(arr, substring)

print(f"The substring '{substring}' occurs {occurrences} times in the array.")


The substring 'hello' occurs 3 times in the array.


57.Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [12]:
import numpy as np

def extract_uppercase_characters(arr):
    """
    Extracts uppercase characters from a NumPy array of strings.

    Parameters:
    arr (np.ndarray): A NumPy array of strings.

    Returns:
    np.ndarray: A NumPy array of strings containing only uppercase characters from the input array.
    """
    # Define a function to extract uppercase characters from a single string
    def extract_uppercase(s):
        return ''.join(c for c in s if c.isupper())
    
    # Apply the function to each element of the array
    uppercase_array = np.vectorize(extract_uppercase)(arr)
    
    return uppercase_array

# Given array
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Extract uppercase characters
uppercase_chars = extract_uppercase_characters(arr)

print("Original array:")
print(arr)
print("\nArray with uppercase characters extracted:")
print(uppercase_chars)


Original array:
['Hello' 'World' 'OpenAI' 'GPT']

Array with uppercase characters extracted:
['H' 'W' 'OAI' 'GPT']


58.Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [13]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    """
    Replaces occurrences of a substring in a NumPy array of strings with a new string.

    Parameters:
    arr (np.ndarray): A NumPy array of strings.
    old_substring (str): The substring to be replaced.
    new_substring (str): The new substring to replace with.

    Returns:
    np.ndarray: A NumPy array with the replaced substrings.
    """
    # Use np.char.replace to perform the replacement
    replaced_array = np.char.replace(arr, old_substring, new_substring)
    
    return replaced_array

# Given array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Substrings to replace
old_substring = 'apple'
new_substring = 'orange'

# Perform the replacement
replaced_array = replace_substring(arr, old_substring, new_substring)

print("Original array:")
print(arr)
print("\nArray with replaced substrings:")
print(replaced_array)


Original array:
['apple' 'banana' 'grape' 'pineapple']

Array with replaced substrings:
['orange' 'banana' 'grape' 'pineorange']


59.Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello', 'World'])

arr2 = np.array(['Open', 'AI'])


In [14]:
import numpy as np

def concatenate_strings_element_wise(arr1, arr2):
    """
    Concatenates strings in two NumPy arrays element-wise.

    Parameters:
    arr1 (np.ndarray): A NumPy array of strings.
    arr2 (np.ndarray): Another NumPy array of strings.

    Returns:
    np.ndarray: A NumPy array with concatenated strings from arr1 and arr2.
    """
    # Use np.char.add to concatenate strings element-wise
    concatenated_array = np.char.add(arr1, arr2)
    
    return concatenated_array

# Given arrays
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Perform the concatenation
concatenated_array = concatenate_strings_element_wise(arr1, arr2)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nConcatenated array:")
print(concatenated_array)


Array 1:
['Hello' 'World']

Array 2:
['Open' 'AI']

Concatenated array:
['HelloOpen' 'WorldAI']


60.Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

   arr = np.array(['apple', 'banana', 'grape', 'pineapple'])


In [15]:
import numpy as np

def longest_string_length(arr):
    """
    Finds the length of the longest string in a NumPy array.

    Parameters:
    arr (np.ndarray): A NumPy array of strings.

    Returns:
    int: The length of the longest string in the array.
    """
    # Find the length of each string in the array
    lengths = np.char.str_len(arr)
    
    # Find the maximum length
    max_length = np.max(lengths)
    
    return max_length

# Given array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Find the length of the longest string
longest_length = longest_string_length(arr)

print(f"The length of the longest string is: {longest_length}")


The length of the longest string is: 9


61.Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [16]:
import numpy as np

# Generate a dataset of 100 random integers between 1 and 1000
data = np.random.randint(1, 1001, size=100)

# Compute mean
mean_value = np.mean(data)

# Compute median
median_value = np.median(data)

# Compute variance
variance_value = np.var(data, ddof=0)  # ddof=0 for population variance

# Compute standard deviation
std_dev_value = np.std(data, ddof=0)  # ddof=0 for population standard deviation

print("Dataset:")
print(data)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_dev_value)


Dataset:
[638 792 115 840 745 549 742 540 315 104 862 447 987  43 240 800 207 847
 918 506 875 189 860 750 498 527 128 172  38 233 330 278 738 794 804 634
 592 474 159 774 336 174  15 341 146   6 897 132 454 962 355 183 491  11
 163 292 335 456 804 332 748 279 868 405 557 283 537 811 283 161 556 666
 897  88 352 459 233 385 508 121 196 581 245 583 908 766 423 823 490 695
  71 909 912 894 879 662 263 699 570 323]

Mean: 490.58
Median: 490.5
Variance: 79331.26359999999
Standard Deviation: 281.65806148590883


62.Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [17]:
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
data = np.random.randint(1, 101, size=50)

# Compute the 25th percentile
percentile_25 = np.percentile(data, 25)

# Compute the 75th percentile
percentile_75 = np.percentile(data, 75)

print("Dataset:")
print(data)
print("\n25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Dataset:
[ 75  83  41  49  60  16  46  94  25   3  11  76  34  25  63  61  48   8
  72  52  66  99  27  94  52  12  59  10 100  73  34  31  71  11  42  83
  58  89   7  61  16  58  73  66  50  14   7  34  29  93]

25th Percentile: 25.5
75th Percentile: 71.75


63.Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [18]:
import numpy as np

# Define two arrays representing two sets of variables
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([15, 25, 35, 45, 55])

# Compute the correlation coefficient matrix
corr_matrix = np.corrcoef(array1, array2)

# Extract the correlation coefficient between the two arrays
corr_coefficient = corr_matrix[0, 1]

print("Correlation Coefficient Matrix:")
print(corr_matrix)
print("\nCorrelation Coefficient between array1 and array2:", corr_coefficient)


Correlation Coefficient Matrix:
[[1. 1.]
 [1. 1.]]

Correlation Coefficient between array1 and array2: 1.0


64.Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [19]:
import numpy as np

# Define two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nMatrix Multiplication Result:")
print(result)


Matrix 1:
[[1 2 3]
 [4 5 6]]

Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]

Matrix Multiplication Result:
[[ 58  64]
 [139 154]]


65.Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

In [20]:
import numpy as np

# Generate an array of 50 random integers between 10 and 1000
data = np.random.randint(10, 1001, size=50)

# Compute the 10th percentile
percentile_10 = np.percentile(data, 10)

# Compute the 50th percentile (median)
percentile_50 = np.percentile(data, 50)

# Compute the 90th percentile
percentile_90 = np.percentile(data, 90)

# Compute the first quartile (25th percentile)
first_quartile = np.percentile(data, 25)

# Compute the third quartile (75th percentile)
third_quartile = np.percentile(data, 75)

print("Dataset:")
print(data)
print("\n10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)



Dataset:
[841  84 419 648 510 603 131 271 899 141 134 937 817 200  55  26 931 141
 990  36 467 705 463 187 595 348 611 688 963 581 476 622 868 131 737 164
 829 969 270 600 125 299 788 422 301 384 658 350 262 480]

10th Percentile: 130.4
50th Percentile (Median): 471.5
90th Percentile: 902.2
First Quartile (25th Percentile): 215.5
Third Quartile (75th Percentile): 700.75


66.Create a NumPy array of integers and find the index of a specific element.

In [21]:
import numpy as np

# Create a NumPy array of integers
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Define the specific element to find
element = 50

# Find the index of the specific element
indices = np.where(array == element)

# `np.where` returns a tuple of arrays, so we extract the first element of the tuple
index = indices[0][0] if len(indices[0]) > 0 else None

print("Array:")
print(array)
print(f"Index of element {element}:", index)


Array:
[ 10  20  30  40  50  60  70  80  90 100]
Index of element 50: 4


67.Generate a random NumPy array and sort it in ascending order.

In [22]:
import numpy as np

# Generate a random NumPy array of integers
random_array = np.random.randint(1, 100, size=10)  # Random integers between 1 and 100, size 10

# Sort the array in ascending order
sorted_array = np.sort(random_array)

print("Original Random Array:")
print(random_array)
print("\nSorted Array:")
print(sorted_array)


Original Random Array:
[ 4 24 22 26 84 13 53 33 18 67]

Sorted Array:
[ 4 13 18 22 24 26 33 53 67 84]


68.Filter elements >20  in the given NumPy array. 
  
   arr = np.array([12, 25, 6, 42, 8, 30])

In [23]:
import numpy as np

# Given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Create a boolean mask for elements greater than 20
mask = arr > 20

# Use the mask to filter the array
filtered_arr = arr[mask]

print("Original Array:")
print(arr)
print("\nFiltered Array (elements > 20):")
print(filtered_arr)


Original Array:
[12 25  6 42  8 30]

Filtered Array (elements > 20):
[25 42 30]


69.Filter elements which are divisible by 3 from a given NumPy array.

    arr = np.array([1, 5, 8, 12, 15])


In [24]:
import numpy as np

# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Create a boolean mask for elements divisible by 3
mask = arr % 3 == 0

# Use the mask to filter the array
filtered_arr = arr[mask]

print("Original Array:")
print(arr)
print("\nFiltered Array (elements divisible by 3):")
print(filtered_arr)


Original Array:
[ 1  5  8 12 15]

Filtered Array (elements divisible by 3):
[12 15]


 70.Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
 
    arr = np.array([10, 20, 30, 40, 50])

 

In [25]:
import numpy as np

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Create a boolean mask for elements ≥ 20 and ≤ 40
mask = (arr >= 20) & (arr <= 40)

# Use the mask to filter the array
filtered_arr = arr[mask]

print("Original Array:")
print(arr)
print("\nFiltered Array (20 ≤ elements ≤ 40):")
print(filtered_arr)


Original Array:
[10 20 30 40 50]

Filtered Array (20 ≤ elements ≤ 40):
[20 30 40]


71.For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

     arr = np.array([1, 2, 3])

In [26]:
import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3])

# Check the byte order using the dtype's byteorder attribute
byte_order = arr.dtype.byteorder

# Interpret the byte order
if byte_order == '>':
    byte_order_str = 'Big-endian'
elif byte_order == '<':
    byte_order_str = 'Little-endian'
elif byte_order == '=':
    byte_order_str = 'Native-endian'
else:
    byte_order_str = 'Unknown'

print("Array:")
print(arr)
print("\nByte Order:", byte_order_str)



Array:
[1 2 3]

Byte Order: Native-endian


72.For the given NumPy array, perform byte swapping in place using `byteswap()`.

    arr = np.array([1, 2, 3], dtype=np.int32)


In [27]:
import numpy as np

# Create the NumPy array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array
print("Original Array:")
print(arr)
print("Original Byte Order:", arr.dtype.byteorder)

# Perform byte swapping in place
arr.byteswap(inplace=True)

# Print the array after byte swapping
print("\nArray After Byte Swapping:")
print(arr)
print("Byte Order After Swapping:", arr.dtype.byteorder)


Original Array:
[1 2 3]
Original Byte Order: =

Array After Byte Swapping:
[16777216 33554432 50331648]
Byte Order After Swapping: =


73.For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.


    arr = np.array([1, 2, 3], dtype=np.int32)

In [28]:
import numpy as np

# Create the NumPy array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original Array:")
print(arr)
print("Original Byte Order:", arr.dtype.byteorder)

# Swap the byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Print the array with swapped byte order and its byte order
print("\nArray With Byte Order Swapped:")
print(swapped_arr)
print("Byte Order After Swapping:", swapped_arr.dtype.byteorder)



Original Array:
[1 2 3]
Original Byte Order: =

Array With Byte Order Swapped:
[16777216 33554432 50331648]
Byte Order After Swapping: >


74.For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.

   arr = np.array([1, 2, 3], dtype=np.int32)

In [29]:
import numpy as np
import sys

# Create the NumPy array with dtype np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's native endianness
native_endian = '='
system_endian = sys.byteorder

# Print the original array and its byte order
print("Original Array:")
print(arr)
print("Original Byte Order:", arr.dtype.byteorder)
print("System Endianness:", system_endian)

# Conditionally swap byte order
if arr.dtype.byteorder != native_endian:
    swapped_arr = arr.newbyteorder()
else:
    swapped_arr = arr.copy()  # No need to swap if already in native endianness

# Print the array with possibly swapped byte order and its byte order
print("\nArray With Byte Order Conditionally Swapped:")
print(swapped_arr)
print("Byte Order After Conditional Swapping:", swapped_arr.dtype.byteorder)


Original Array:
[1 2 3]
Original Byte Order: =
System Endianness: little

Array With Byte Order Conditionally Swapped:
[1 2 3]
Byte Order After Conditional Swapping: =


75.For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.

  arr = np.array([1, 2, 3], dtype=np.int32)

In [31]:
import numpy as np
import sys

# Given NumPy array
arr = np.array([1, 2, 3], dtype=np.int32)

# Check the system's native endianness
system_endian = sys.byteorder

# Determine the byte order of the array
array_byte_order = arr.dtype.byteorder

# Determine if byte swapping is necessary
if array_byte_order == '=':
    # Native endianness; no swap needed
    byte_swap_needed = False
elif (array_byte_order == '<' and system_endian == 'little') or \
     (array_byte_order == '>' and system_endian == 'big'):
    # Array and system endianness are the same
    byte_swap_needed = False
else:
    # Byte order differs from system endianness
    byte_swap_needed = True

# Print results
print("Original Array:")
print(arr)
print("Array Byte Order:", array_byte_order)
print("System Endianness:", system_endian)
print("Byte Swap Needed:", byte_swap_needed)


Original Array:
[1 2 3]
Array Byte Order: =
System Endianness: little
Byte Swap Needed: False


76.Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [32]:
import numpy as np

# Create the original NumPy array
arr1 = np.arange(1, 11)

# Create a copy of arr1
copy_arr = arr1.copy()

# Print the original array and its copy before modification
print("Original Array (arr1):")
print(arr1)

print("\nCopy of Array (copy_arr) before modification:")
print(copy_arr)

# Modify an element in the copy
copy_arr[0] = 100

# Print the original array and its copy after modification
print("\nCopy of Array (copy_arr) after modification:")
print(copy_arr)

print("\nOriginal Array (arr1) after modification in copy:")
print(arr1)


Original Array (arr1):
[ 1  2  3  4  5  6  7  8  9 10]

Copy of Array (copy_arr) before modification:
[ 1  2  3  4  5  6  7  8  9 10]

Copy of Array (copy_arr) after modification:
[100   2   3   4   5   6   7   8   9  10]

Original Array (arr1) after modification in copy:
[ 1  2  3  4  5  6  7  8  9 10]


77.Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [33]:
import numpy as np

# Create a 2D NumPy array with random integers of shape (3, 3)
matrix = np.random.randint(1, 10, size=(3, 3))

# Print the original matrix
print("Original Matrix:")
print(matrix)

# Extract a slice from the matrix (e.g., the sub-array of the first two rows and columns)
view_slice = matrix[:2, :2]

# Print the slice before modification
print("\nView Slice Before Modification:")
print(view_slice)

# Modify an element in the view_slice
view_slice[0, 0] = 999

# Print the slice and the original matrix after modification
print("\nView Slice After Modification:")
print(view_slice)

print("\nOriginal Matrix After Modification in Slice:")
print(matrix)


Original Matrix:
[[1 7 6]
 [8 7 2]
 [5 4 5]]

View Slice Before Modification:
[[1 7]
 [8 7]]

View Slice After Modification:
[[999   7]
 [  8   7]]

Original Matrix After Modification in Slice:
[[999   7   6]
 [  8   7   2]
 [  5   4   5]]


78.Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`

In [34]:
import numpy as np

# Create a NumPy array with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape((4, 3))

# Print the original array
print("Original Array (array_a):")
print(array_a)

# Extract a slice from array_a
view_b = array_a[:2, :2]

# Print the slice before modification
print("\nView Slice Before Modification (view_b):")
print(view_b)

# Add 5 to the slice using broadcasting
view_b += 5

# Print the slice and the original array after modification
print("\nView Slice After Broadcasting Addition:")
print(view_b)

print("\nOriginal Array After Modification in Slice (array_a):")
print(array_a)


Original Array (array_a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

View Slice Before Modification (view_b):
[[1 2]
 [4 5]]

View Slice After Broadcasting Addition:
[[ 6  7]
 [ 9 10]]

Original Array After Modification in Slice (array_a):
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


79.Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [36]:
import numpy as np

# Create the original NumPy array with values from 1 to 8
orig_array = np.arange(1, 9).reshape((2, 4))

# Print the original array
print("Original Array (orig_array):")
print(orig_array)

# Create a reshaped view of shape (4, 2) from orig_array
reshaped_view = orig_array.reshape((4, 2))

# Print the reshaped view before modification
print("\nReshaped View Before Modification (reshaped_view):")
print(reshaped_view)

# Modify an element in the reshaped view
reshaped_view[0, 0] = 999

# Print the reshaped view and the original array after modification
print("\nReshaped View After Modification:")
print(reshaped_view)

print("\nOriginal Array After Modification in View (orig_array):")
print(orig_array)


Original Array (orig_array):
[[1 2 3 4]
 [5 6 7 8]]

Reshaped View Before Modification (reshaped_view):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Reshaped View After Modification:
[[999   2]
 [  3   4]
 [  5   6]
 [  7   8]]

Original Array After Modification in View (orig_array):
[[999   2   3   4]
 [  5   6   7   8]]


80.Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [37]:
import numpy as np

# Create a NumPy array with random integers of shape (3, 4)
data = np.random.randint(1, 10, size=(3, 4))

# Print the original array
print("Original Data Array (data):")
print(data)

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Print the copy before modification
print("\nData Copy Before Modification (data_copy):")
print(data_copy)

# Modify an element in the data copy
data_copy[0] = 999

# Print the copy and the original array after modification
print("\nData Copy After Modification:")
print(data_copy)

print("\nOriginal Data Array After Modification in Copy (data):")
print(data)


Original Data Array (data):
[[3 4 5 3]
 [5 6 7 9]
 [2 3 8 1]]

Data Copy Before Modification (data_copy):
[6 7 9 8]

Data Copy After Modification:
[999   7   9   8]

Original Data Array After Modification in Copy (data):
[[3 4 5 3]
 [5 6 7 9]
 [2 3 8 1]]


81.Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [38]:
import numpy as np

# Create two matrices A and B of identical shape with integers
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Perform addition
addition_result = A + B

# Perform subtraction
subtraction_result = A - B

# Print the results
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition Result (A + B):")
print(addition_result)

print("\nSubtraction Result (A - B):")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition Result (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction Result (A - B):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


82.Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [39]:
import numpy as np

# Create matrix C of shape (3, 2)
C = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])

# Create matrix D of shape (2, 4)
D = np.array([[7, 8, 9, 10], 
              [11, 12, 13, 14]])

# Perform matrix multiplication
result = np.dot(C, D)

# Print the matrices and the result
print("Matrix C:")
print(C)

print("\nMatrix D:")
print(D)

print("\nMatrix Multiplication Result (C @ D):")
print(result)


Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

Matrix Multiplication Result (C @ D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


83.Create a matrix `E` and find its transpose.

In [40]:
import numpy as np

# Create matrix E
E = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Find the transpose of the matrix E
E_transpose = np.transpose(E)

# Print the original matrix and its transpose
print("Matrix E:")
print(E)

print("\nTranspose of Matrix E (E^T):")
print(E_transpose)


Matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix E (E^T):
[[1 4 7]
 [2 5 8]
 [3 6 9]]


84.Generate a square matrix `F` and compute its determinant.

In [41]:
import numpy as np

# Create another square matrix F
F = np.array([[4, 2, 3], 
              [3, 5, 6], 
              [7, 8, 9]])

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)

# Print the original matrix and its determinant
print("Matrix F:")
print(F)

print("\nDeterminant of Matrix F:")
print(determinant_F)


Matrix F:
[[4 2 3]
 [3 5 6]
 [7 8 9]]

Determinant of Matrix F:
-15.000000000000007


85.Create a square matrix `G` and find its inverse.

In [42]:
import numpy as np

# Create another square matrix G
G = np.array([[1, 2, 3], 
              [0, 1, 4], 
              [5, 6, 0]])

# Compute the inverse of matrix G
G_inverse = np.linalg.inv(G)

# Print the original matrix and its inverse
print("Matrix G:")
print(G)

print("\nInverse of Matrix G (G^-1):")
print(G_inverse)


Matrix G:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Inverse of Matrix G (G^-1):
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
